version: "3"
services:
    #ui-service:
    #    container_name: adamstoreclient
    #    image: registry.gitlab.com/lehoa08121998/adamstoreclient/main:latest
    #    ports: 
    #      - "80:80"
    dotnet-app:
        container_name: dotnet-core5.0
        image: registry.gitlab.com/lehoa08121998/adamstore/main:latest
        ports:
            - '5000:5000'
        depends_on:
            - ms-sqlserver
        entrypoint: dotnet API.dll
    ms-sqlserver:
        container_name: ms-sqldb1
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1433:1433
        environment:
           - ACCEPT_EULA=Y
           - SA_PASSWORD=Secret123!@#