version: "3"
services:
    ui-service:
        container_name: adamstoreclient
        image: registry.gitlab.com/lehoa08121998/adamstoreclient/main:latest
        ports: 
          - "80:80"
        networks:
          - adamstore
    dotnet-app:
        container_name: dotnet-core5.0
        image: registry.gitlab.com/lehoa08121998/adamstore/main:latest
        ports:
            - '5000:5000'
        depends_on:
            - ms-sqlserver
        entrypoint: dotnet API.dll
        networks:
          - adamstore
    ms-sqlserver:
        container_name: ms-sqldb
        image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Secret123!@#"
          MSSQL_PID: Express
        ports:
           - "1433:1433"
        volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
        networks:
          - adamstore
volumes:
    sqlsystem:
    sqldata:
    sqllog:
    sqlbackup:
networks:
    adamstore: